modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/Pronounced/issues"
license="MIT"

[[mods]]
modId="pronounced"
version="${file.jarVersion}"
displayName="Pronounced"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pronounced"
authors="Mrbysco, Kara2810"
description='''
It's pronounced Fractionis not Fractionus
'''

[[dependencies.pronounced]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.pronounced]]
modId="spelled"
mandatory=true
versionRange="[0.6.2.1,)"
ordering="NONE"
side="BOTH"